### PR TITLE
thaotran_message.py

### PR DESCRIPTION
**Pull request by thaotran9**

### CODE REVIEW

**Review by Boneill3 — APPROVED** [review]
Looks good! Great finds!

**Review by nhanlt81 — APPROVED** [review]
Looks good, Thao

**Comment by Sanlinlin** [comment]
Looks good~

**Review by TheDragonMask — APPROVED** [review]
Great find! Also it looks like the range of values at the top here is what everyone's been saying I should use in my changes to pdo.py and sdo.py, so it's good I've found them here just by naturally wrapping up code reviews.

**Pull request merged**
